nodeLinker: node-modules
enableTelemetry: false
enableGlobalCache: true

logFilters:
  - level: discard
    pattern: "*is deprecated*"
  - level: discard  
    pattern: "*This version is no longer supported*"
  - level: discard
    pattern: "*has incorrect peer dependency*"
  - level: discard
    pattern: "*Resolution field*"
